import type { Metadata } from "next";
import { Inter, Kumbh_Sans, Roboto_Serif, Krona_One } from "next/font/google";
import "./globals.css";
import MenuProvider from "../context/useContextMenu";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import ScreenBreakPointProvider from "@/context/useScreenBreakPoints";
const inter = Inter({ subsets: ["latin"] });
const kumbhSans = Kumbh_Sans({ subsets: ["latin"] });
const robotoSerif = Roboto_Serif({ subsets: ["latin"] });
const kronaOne = Krona_One({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`
                ${kumbhSans.className} 
                ${robotoSerif.className}                    
                ${inter.className} 
                ${kronaOne.className}
                `}
            >
                <ScreenBreakPointProvider>
                    <MenuProvider>
                        <Header />
                        {children}
                        <Footer />
                    </MenuProvider>
                </ScreenBreakPointProvider>
            </body>
        </html>
    );
}
