import type { Metadata } from "next";
import { Inter, Kumbh_Sans, Roboto_Serif, Krona_One } from "next/font/google";
import "./globals.css";
import MenuProvider from "../lib/context/useContextMenu";
import ModalProvider from "../lib/context/useContextModal";
import ScreenBreakPointProvider from "../lib/context/useContextScreenBreakPoints";
import Footer from "../components/layout/Footer";
import Header from "@/components/header";
import NavMenu from "../components/layout/NavMenu";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const kumbhSans = Kumbh_Sans({ subsets: ["latin"], variable: "--font-kumbh-sans" });
const robotoSerif = Roboto_Serif({ subsets: ["latin"], variable: "--font-roboto-serif" });
const kronaOne = Krona_One({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-krona-one",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`
                ${kumbhSans.variable} 
                ${robotoSerif.variable}                    
                ${inter.variable} 
                ${kronaOne.variable}
                font-robotoSerif
                `}
            >
                <ModalProvider>
                    <ScreenBreakPointProvider>
                        <MenuProvider>
                            <NavMenu />
                            <Header />
                            {children}
                            <Footer />
                        </MenuProvider>
                    </ScreenBreakPointProvider>
                </ModalProvider>
            </body>
        </html>
    );
}
